---
title: "Clean data"
format: html
editor: source
author: authors
---

### Source functions

```{r}
source("../R/99_proj_func.R")
```

### Libraries:

```{r}
#| message: false
library("tidyverse")
library(vroom)
```

### Clean

```{r}

feature_data <- vroom("../data/01_feature_data.tsv.gz", delim = "\t")
pheno_data <- vroom("../data/01_pheno_data.tsv.gz", delim = "\t")
norm_exprs <- vroom("../data/01_norm_exprs.tsv.gz")

ncbi_data <- read_tsv("../data/01_ncbi_data.tsv.gz")
ncbi_annot_probes <- read_tsv("../data/01_ncbi_annot_probes.tsv.gz")
```

```{r}

feature_data |> sample_n(5)
pheno_data |> sample_n(5)
norm_exprs |> sample_n(5)
ncbi_data |> sample(5)

```

### Phenotypic clean file stuff

```{r}
clean_pheno_data <- pheno_data |>
  rename("sample_id" = "geo_accession") |>
  rename(
    "Mother_age_years" = "age..years..ch1",
    "apgar_score" = "apgar.score..5s..ch1",
    "cord_blood_cotinine_ng_ml" = "cord.blood.cotinine..ng.ml..ch1",
    "gestational_age_weeks" = "gestational.age..weeks..ch1",
    "maternal_blood_cotinine_ng_ml" ="maternal.blood.cotinine..ng.ml..ch1",
    "maternal_bmi" = "maternal.bmi.ch1",
    "smoking_status" = "smoking.status.ch1",
    "newborn_weight_g"="newborn.weight..g..ch1") |>
  select("sample_id",
         "Mother_age_years",
         "apgar_score",
         "cord_blood_cotinine_ng_ml",
         "gestational_age_weeks",
         "maternal_blood_cotinine_ng_ml",
         "maternal_bmi",
         "smoking_status",
         "newborn_weight_g",
         "sex",
         "description")
```

### Raw phenotype extraction from NCBI (Masha, Einstein & Magnus)

```{r}
ncbi_clean_data <- ncbi_pheno_data

## Magnus
#Choose relevant data
ncbi_dirty_pheno <- ncbi_pheno_data |> 
  as_tibble() |>
  filter(!str_detect(col_1, 
                     "ILMN")) |>
  filter(!str_detect(col_1, 
                     "ID_REF")) |>
  slice(41:n()) |>
  t()
#Rename coloums
colnames(ncbi_dirty_pheno) <- ncbi_dirty_pheno[1, ] |> 
  stringr::str_replace_all("!Sample_","")

#Add colnames to 
ncbi_dirty_pheno <- ncbi_dirty_pheno[-1, ] |> 
  as_tibble() |>
  rename_with(tolower, 
              .cols = everything()) 

colnames(ncbi_dirty_pheno)

# more data wrangling
ncbi_clean_pheno <- ncbi_dirty_pheno |>
  # Choose important coloums to further wrangle. 
  select(matches(
    "geo_accession|title|characteristics_ch1|v11|v12|v13|v14|v15|v16|v17|v18|v19|v20|v21|v22")
    ) |>
  # mutate coloumn name and variable string
  mutate(
    smoking_status = str_remove(
      v11, "smoking status: "),
    tissue = str_remove(characteristics_ch1, "tissue: "),
    age = as.numeric(str_remove(
      v12, "age \\(years\\): ")),
    maternal_bmi = as.numeric(str_remove(
      v13, "maternal bmi: ")),
    parity = str_remove(v14, "parity: "),
    gestational_age = as.numeric(str_remove(
      v15, "gestational age \\(weeks\\): ")),
    birth_type = str_remove(
      v16, "mode of delivery: "),
    placental_weight = as.numeric(str_remove(
      v17, "placental weight \\(g\\): ")),
    newborn_weight = as.numeric(str_remove(
      v18, "newborn weight \\(g\\): ")),
    apgar_score = as.numeric(str_remove(
      v19, "apgar score \\(5s\\): ")),
    cotinine_conc_maternal = as.numeric(str_remove(
      v20, "maternal blood cotinine \\(ng/ml\\): ")),
    cotinine_conc_cord = as.numeric(str_remove(
      v21, "cord blood cotinine \\(ng/ml\\): ")),
    individual = str_remove(
      v22, "individual: ")) |>
  # Keep new columns
  select(-matches("characteristics_ch1|v11|v12|v13|v14|v15|v16|v17|v18|v19|v20|v21|v22")
         ) |>
  t() |> 
  as.data.frame() |>
  rename_with(~str_replace_all(., "V", ""), .cols = everything()
              ) |>
  t()

######################
ncbi_dirty_data <- ncbi_pheno_data[88:nrow(ncbi_pheno_data), , 
                                   drop = FALSE]
colnames(ncbi_dirty_data) <- ncbi_dirty_data[1, ]
ncbi_dirty_data <- ncbi_dirty_data[-1, ] |>
  t()

#Add colnames to 
ncbi_clean_data <- ncbi_dirty_data

ncbi_clean_data <- ncbi_dirty_data[-1,] |> 
  as.data.frame() |>
  rename_with(tolower, 
              .cols = everything()) 

## Oliver

#Firstly chosing the right rows and transposing
ncbi_pheno_data_impure <- ncbi_pheno_data[1:86,] |> t()

#Then choosing the right columns and making as tibble
ncbi_pheno_data_impure_cut <- ncbi_pheno_data_impure[,41:86] |> as_tibble()


#Removing ! from the names and Convert first row to header
colnames(ncbi_pheno_data_impure_cut) <- ncbi_pheno_data_impure_cut[1, ] |>
  stringr::str_replace_all("!", "")

ncbi_pheno_data_impure_cut_renamed



ncbi_pheno_data_impure_cut |> View()
is.data.frame(ncbi_pheno_data_impure_cut) 


```

### Boxplots showing normalization

```{r}

# BOXPLOTS to check NORMALIZATION

# check ncbi data (original)
b_raw <- ncbi_data[89:nrow(ncbi_data), 2:10] |> 
  mutate_all(as.numeric) |>
  boxplot()


# Kaggle normalized data
b <- norm_exprs[1:nrow(norm_exprs), 1:10] |> 
  boxplot()


# RAW NON NORMALIZED PLACENTA FILE
file_n <- "GSE27272_non-normalized_placenta.txt.gz"
raw_dir <- "../_raw/"
non-normalized_placenta <- read.table(gzfile(str_c(raw_dir, file_n)))
non-normalized_placenta[2:nrow(non-normalized_placenta), 2:10] |> 
  mutate_all(as.numeric) |> 
  boxplot()

       
```

### Extract gene expression

```{r}
# extract gene expression from ncbi data

gene_exp_idx <- 89

gene_exp <- ncbi_data |> 
  slice(gene_exp_idx:nrow(ncbi_data))
  
colnames(gene_exp) <-
  ncbi_data |> 
  slice(88) |>
  unlist()
        
gene_exp <- gene_exp |> 
  rename(probe_id = ID_REF) |>
  mutate(across(-probe_id, ~ as.numeric(.x)))


###### Nicer boxplot to show normalization
gene_exp_longer <- gene_exp  |> 
  select(1:10) |> 
  pivot_longer(
    cols = starts_with("GSM"),
    names_to = "sample_id",
    values_to = "gene_expression"
  )

ggplot(data=gene_exp_longer, mapping=aes(x=sample_id, y=gene_expression)) +
  geom_boxplot()
```

### Split gene expression by source of the samples

```{r}
# extract important columns from annotation

gene_annotation <- ncbi_annot_probes |> 
  select(Symbol, Probe_Id, Definition, Entrez_Gene_ID, starts_with("Ontology"))

gene_exp <- gene_annotation |> 
  select(Symbol, Probe_Id) |> 
  right_join(gene_exp, by=c('Probe_Id'='probe_id')) |> 
  rename(Gene = Symbol) |> 
  select(-Probe_Id)

####### need ncbi_pheno_data_impure_cut df

sample_source_table <- ncbi_pheno_data_impure_cut |>
  select(Sample_geo_accession, 30) |>  # 30 = Sample_description
  mutate(sample_source = str_match(Sample_description, "[[:upper:]]+")) |> 
  rename(sample_id = Sample_geo_accession) |> 
  select(-Sample_description)

# gene_exp_placenta
gene_exp_placenta <- get_gene_expr_by_source(gene_exp, sample_source_table, "PL")

# gene_exp_maternal_blood
gene_exp_maternal_blood <- get_gene_expr_by_source(gene_exp, sample_source_table, "M")

# gene_exp cord blood
gene_exp_cord_blood <- get_gene_expr_by_source(gene_exp, sample_source_table, "D")
```

```{r}

length(unique(rownames(gene_exp_placenta)))
length(rownames(gene_exp_placenta))

gene_exp_placenta |> t()

placenta_mat <- gene_exp_placenta |> t()
gene_names <- placenta_mat[1]
sample_ids <- rownames(placenta_mat)

placenta_tibble <- gene_exp_placenta |> 
  t() |> 
  as_tibble()
colnames(placenta_tibble) <- placenta_tibble |> 
  slice(1)
#placenta_tibble <- placenta_tibble 
placenta_tibble <- placenta_tibble |>
  as_tibble(.name_repair="minimal")
placenta_tibble <- placenta_tibble[2:nrow(placenta_tibble), ]

placenta <- gene_exp_placenta |> t() |> as_data_frame()
length(unique(colnames(placenta)))
length(colnames(placenta))



#|> as_tibble()
colnames(placenta) <- placenta |>
  slice(1) |> 
  as.character()
placenta
placenta <- placenta |>
  tail(-1)

colnames(placenta_tibble) <- colnames(placenta)

cols <- colnames(gene_exp_placenta) |> as_tibble() |> 
  slice(-1)
nrow(placenta)

cols <- cols |> 
  unlist()

names(cols) <- NULL

length(cols)

cols

rownames(placenta) <- cols
```

```{r}
placenta |> 
  slice(2:nrow(placenta))
colnames(placenta)

names(placenta_tibble) <- unlist(placenta[1, ])

placenta_tibble |> rename_with(~unlist(placenta[1, ]))
names(placenta)

length(unique(colnames(placenta_tibble)))
length()

placenta$JMJD1A
placenta$NCOA3

################


placenta_tibble <- placenta_tibble[1:10]
names(placenta_tibble) <- unlist(placenta[1, ])
placenta_tibble <- placenta_tibble |> 
  slice(-1)

placenta_tibble  |>  
  pivot_longer(cols=1:10, names_to = "variable", values_to = "values") |> 
  ggplot(aes(JMJD1A, values)) + 
  geom_point() + 
  facet_grid(. ~ variable, scales = "free_x") + 
  geom_smooth(method = "lm", se = FALSE) + 
  scale_y_continuous(trans = "log2") + 
  scale_x_continuous(trans = "log2")


#facet_grid(. ~ variable, scales = "free_x") + 
  
```

```{r}
df <- read.table(text = "
LINP1   EGFR            RB1       TP53         CDKN2A      MYC
Sample1 0.02   0.038798682  0.1423662   2.778587067 0.471403939 18.93687655
Sample2 0      0.059227225  0.208765213 0.818810739 0.353671882 1.379027685
Sample3 0      0.052116384  0.230437735 2.535040249 0.504061015 9.773089223
Sample4 0.06   0.199264618  0.261100548 2.516963635 0.63659138  11.01441624
Sample5 0      0.123521916  0.273330986 2.751309388 0.623572499 34.0563519
Sample6 0      0.128767634  0.263491811 2.882878373 0.359322715 13.02402045
Sample7 0      0.080097356  0.234511372 3.568192768 0.386217698 9.068928569
Sample8 0      0.017421323  0.247775683 5.109428797 0.068760572 15.7490551
Sample9 0      2.10281137   0.401582013 8.202902242 0.140596724 60.25989178", header = TRUE)


placenta_tibble[1:10] |> 
  mutate_all(as.numeric) |>
  gather(key = variable, value = values, NCOA3:10) |> 
  ggplot(aes(JMJD1A, values)) + 
  geom_point() + 
  facet_grid(. ~ variable, scales = "free_x") + 
  geom_smooth(method = "lm", se = FALSE) + 
  scale_y_continuous(trans = "log2") + 
  scale_x_continuous(trans = "log2") +
  labs(x="Gene expression of JMJD1A", y="Gene expression")

# https://stackoverflow.com/questions/51195960/how-to-make-a-scatterplot-showing-correlation-between-a-single-gene-vs-multiple


```

```{r}

sample_ids <- colnames(gene_exp_placenta)[2:length(colnames(gene_exp_placenta))]

placenta_tibble[1:10] |> 
  mutate_all(as.numeric) |>
  mutate(ids = sample_ids) |> 
  relocate(ids)

placenta_tibble[1:10] |> 
  mutate_all(as.numeric) |>
  mutate(ids = sample_ids) |> 
  relocate(ids) |> 
  left_join()
  mutate(smoker = )
  gather(key = variable, value = values, NCOA3:10) |> 
  ggplot(aes(JMJD1A, values)) + 
  geom_point() + 
  facet_grid(. ~ variable, scales = "free_x") + 
  geom_smooth(method = "lm", se = FALSE) + 
  scale_y_continuous(trans = "log2") + 
  scale_x_continuous(trans = "log2") +
  labs(x="Gene expression of JMJD1A", y="Gene expression")
```

```{r, fig.width=12, fig.height=8}
library(corrplot)

placenta_numeric <- placenta_tibble[1:10] |> 
  mutate_all(as.numeric)

corrplot(cor(placenta_numeric),
  type = "upper" # show only upper side
)
```

```{r}
ncbi_data[89:nrow(ncbi_data), ]
```

```{r}
gene_annotation |> 
  filter(Symbol=="NCOA3")
```
