### Source functions

```{r}
source("../R/99_proj_func.R")
```

### Library:

```{r}
#| message: false
library("tidyverse")
library("ggridges")
library("viridis")
library("broom")
library("ggrepel")
library(corrplot)
```

### loading:

```{r}
#| eval: true
#| message: false

pheno_data <- vroom::vroom("../data/04_ncbi_augment_pheno.tsv.gz",
                           delim = "\t")

# we haven't augmented expr (Masha)
# expr_data <- vroom::vroom("../data/04_ncbi_augment_expr.tsv.gz", delim = "\t")

ncbi_joined <- vroom::vroom("../data/04_ncbi_joined.tsv.gz",
                             delim = "\t")

ncbi_smoking_logfc_cord <- vroom::vroom("../data/04_ncbi_smoking_logfc_cord_blood.tsv.gz",
                                 delim = "\t")

pheno_data |> 
  sample_n(5)
ncbi_joined |> 
  sample_n(5)
ncbi_joined_aug |> 
  sample_n(5)
ncbi_smoking_logfc_cord |> 
  sample_n(5)
```

### Data statistics:

```{r}

joined_colnames <- ncbi_joined |> 
  colnames()

auged_norm_exprs_00 <- ncbi_joined |> 
  dplyr::select(-joined_colnames[1],
                -joined_colnames[5:15]) |>
  mutate(is_smoker = case_when(str_detect(smoking_status, 
                                          "non") == 1 ~ 0,
                               str_detect(smoking_status, 
                                          "non") == 0 ~ 1),
         .before = 1) |>
  dplyr::select(-smoking_status)

auged_norm_exprs_01 <- auged_norm_exprs_00 |>
  pivot_longer(cols = colnames(auged_norm_exprs_00[4:1000]),
               names_to = "gene",
               values_to = "expr_level") |>
  mutate(log_2_expr_level =log2(expr_level)) |>
  dplyr::select(-expr_level)

auged_norm_exprs_02 <- auged_norm_exprs_01 |>
  group_by(gene) |>
  nest() |>
  ungroup()

# updating data frame. First we group rows by gene, and then we add a variable containing model fitted to expression level against early_metastasis variable
auged_norm_exprs_03 <- auged_norm_exprs_02 |>
  group_by(gene) |>
  mutate(model_object = map(.x = data,
                            .f = ~lm(formula = log_2_expr_level ~ is_smoker,
                                     data = .x))) |>
  
# using tidy function to turn model summary into a tibble instead of a list  
  mutate(model_object_tidy = map(.x = model_object,
                                 .f = ~ tidy(.x,
                                             conf.int = TRUE,
                                             conf.level = 0.95)))

# unnesting the tidy models, filtering to only get "slope"-coefficients for models and selecting desired variables
auged_norm_exprs_04 <- auged_norm_exprs_03 |>
  unnest(model_object_tidy) |>
  filter(term == "is_smoker") |>
  dplyr::select(gene, 
                p.value, 
                estimate, 
                conf.low, 
                conf.high) |>
  ungroup() |>
  
# creating variables "q-value" which is the p-value adjusted for multiple comparisons and "is_significant" which indicates whether observations are statistically significant when using a level of significance of 0.0
  mutate(is_significant = case_when(
           p.value < 0.05 ~ "yes",
           0.05 < p.value ~ "no"
         ))
```

### Volcano plot:

```{r}
significant_labels <- subset(auged_norm_exprs_04 , 
                          is_significant == "yes") |>
  dplyr::select(gene)

auged_norm_exprs_04 |>
  ggplot(aes(x = gene,
             y = -log(p.value,10),
             label = ifelse(is_significant == "yes", 
                            gene, 
                            ""))) + 
  geom_point(aes(x = estimate, 
                 color = is_significant),
             alpha = .5,
             size=1) +
  geom_hline(yintercept = 0) +
  theme_minimal(base_size = 10) +
  labs(title = "Genes Associated with",
       subtitle = "Genes highlighted in turquoise were significant after multiple testing correction",
       x = "Estimates",
       y = "-log10(p)") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = .95),
        plot.subtitle = element_text(hjust = .95)) +
  facet_wrap(~antibiotic, 
             scales = "free_y", 
             ncol = 2,
             strip.position = "top",
             labeller = as_labeller(c(cipro = "P. putida strain B - Ciprofloxacin", 
                                      oflo = "P. putida strain B - Ofloxacin")))
```

## more rangling:

```{r}

# General exprs of all genes comparing smoking

# non functional(Masha)

ncbi_joined |> select(-joined_colnames[1:2],
                        -joined_colnames[4:15]) |>
  pivot_longer(cols = joined_colnames[16:1000],
               names_to = "gene",
               values_to = "expr_level") |>
  sample_n(20) |>
  ggplot(aes(expr_level, 
             fill = smoking_status)) +
  geom_boxplot()
```

### Gene association plot:

```{r}

auged_norm_exprs_04 |>
  filter(is_significant == "yes") |>
  ggplot(aes(y = fct_reorder(gene,estimate))) + 
  geom_point(aes(x = estimate), 
             size=1.5) +
  geom_errorbarh(aes(xmax = conf.high,
                     xmin = conf.low),
                     height = 1) +
  geom_vline(xintercept = 0) +
  theme_minimal(base_size = 10) +
  theme(legend.position = "bottom") +
  labs(title = "Genes Associated with Smoking",
       x = "Estimates (95%CIs)",
       y = "",)
```

We can generrely see that when a person smokes there is a major downregulation of some genes. Some are also upregulated. We cant tell the effect of the regulation

```{r}
num_genes_to_compare <- 6
genes_start_idx = 16

ncbi_joined |>
  select(smoking_status, genes_start_idx : (genes_start_idx + num_genes_to_compare)) |> 
  pivot_longer(names_to = "variable", values_to = "values", 3:last_col()) |> 
  ggplot(aes(JMJD1A, values)) + 
  geom_point(aes(color=smoking_status)) + 
  facet_grid(. ~ variable, scales = "free_x") + 
  geom_smooth(method = "lm", se = FALSE) + 
  scale_y_continuous(trans = "log2") + 
  scale_x_continuous(trans = "log2") +
  labs(
    x="Gene expression of JMJD1A",
    y="Gene expression",
    title = "Gene expression of 6 genes plotted against the gene expression of gene JMJD1A")
```

### Gene expression correlation

```{r}

genes_cord_blood <- ncbi_joined |> 
  mutate(sample_source = str_match(title, "[[:upper:]]+")) |>
  filter(sample_source == "D") |> 
  select(16:30)

corrplot(cor(genes_pl),
  type = "upper"
)
```

### Log Fold Change

```{r}

gene_exp_cord_blood <- ncbi_joined |> 
  mutate(sample_source = str_match(title, "[[:upper:]]+")) |>
  filter(sample_source == "D") |> 
  select(3, 16:last_col()-1)

# calculate mean expressions of genes for both statuses of smoking
mean_expression_nonsmoker <- gene_exp_cord_blood |>
  filter(smoking_status == "non-smoker") |> 
  select(-1) |> 
  colMeans()
mean_expression_smoker <- gene_exp_cord_blood |>
  filter(smoking_status == "smoker") |> 
  select(-1) |> 
  colMeans()

# calculate log fold change
smoking_fold_change <-
  tibble(mean_expression_nonsmoker, mean_expression_smoker) |>  
  mutate(Gene = names(mean_expression_nonsmoker)) |> 
  relocate(Gene) |> 
  mutate(log_fold_change = log2(mean_expression_smoker) - log2(mean_expression_nonsmoker))

smoking_fold_change |>
  arrange(desc(log_fold_change))
```

```{r}
smoking_fold_change |> 
  arrange(desc(abs(log_fold_change)))

ncbi_smoking_logfc_cord |> 
  arrange(desc(abs(log_fold_change))) |> 
  slice_head(n=5)
```
