### Source functions

```{r}
source("../R/99_proj_func.R")
```

### Library:

```{r}
#| eval: false 
#| echo: true
#| message: false
library("tidyverse")
library("ggridges")
library("viridis")
library("broom")
library("ggrepel")
```

### loading:

```{r}
#| eval: true
#| echo: true
#| message: false

pheno_data <- vroom::vroom("../data/04_ncbi_augment_pheno.tsv.gz",
                           delim = "\t")

# we haven't augmented expr (Masha)
# expr_data <- vroom::vroom("../data/04_ncbi_augment_expr.tsv.gz", delim = "\t")

ncbi_joined <- vroom::vroom("../data/04_ncbi_joined.tsv.gz",
                             delim = "\t")
ncbi_joined_aug <- vroom::vroom("../data/04_ncbi_joined_aug.tsv.gz",
                                 delim = "\t")
pheno_data |> 
  sample_n(5)
ncbi_joined |> 
  sample_n(5)
ncbi_joined_aug |> 
  sample_n(5)
```


### plotting:

```{r}
#| eval: false 
#| echo: true

## Magnus

# SKRALD
# SKRALD
# SKRALD

ggplot(data = ncbi_joined_aug,
       mapping = aes(x = newborn_weight,
                     y = log2(cotinine_conc_maternal))) +
  geom_point(aes(color = age_group,
                 size = factor(BMI_class,
                               levels = c("Severely underweight",
                                          "Underweight",
                                          "Normal weight", 
                                          "Overweight",
                                          "Obesity", 
                                          "Obesity class I",
                                          "Obesity class II", 
                                          "Obesity class III")))) + 
  labs(title = "Comparision of smoking severity and newborn weight",
       x = "Newborn Weight (g)",
       y = "Log2 of cotinine_conc_maternal",
       color = "Age Group",
       size = "BMI class",
       caption = "Data from NCBI (2011)") +
  theme_minimal(base_family = "Avenir") + 
  theme(legend.position = "right") 

# GULD
# GULD
# GULD
ggplot(data = ncbi_joined_aug,
       mapping = aes(x = smoking_status,
                     y = newborn_weight,
                     fill = smoking_status)) +
  geom_boxplot() +
  labs(title = "Investigating Effect of Smoking on Newborn",
       subtitle = "Comparision of newborn weight and smoking status",
       x = "",
       fill = "",
       y = "Newborn Weight (g)",
       caption = "Data from NCBI (2011)") +
  theme_minimal(base_family = "Avenir") + 
  theme(legend.position = "none") 


#
ggplot(data = ncbi_joined_aug,
       mapping = aes(x = newborn_weight,
                     y = placental_weight)) +
  geom_point(aes(color = smoking_status,
                 size = factor(BMI_class,
                               levels = c("Severely underweight",
                                          "Underweight",
                                          "Normal weight", 
                                          "Overweight",
                                          "Obesity", 
                                          "Obesity class I",
                                          "Obesity class II", 
                                          "Obesity class III")))) + 
  geom_hline(aes(yintercept = mean(placental_weight)),
             alpha = 0.4,
             linetype="dashed",
             color = "purple", 
             size=0.5) +
  geom_vline(aes(xintercept = mean(newborn_weight)),
             alpha = 0.4,
             linetype="dashed",
             color = "purple", 
             size=0.5) +
  labs(title = "Weight comparison",
       subtitle = "Measured in grams",
       x = "Newborn",
       y = "Placental",
       color = "Smoking Status",
       size = "BMI class",
       caption = "Data from NCBI (2011)") +
  theme_minimal(base_family = "Avenir") + 
  theme(legend.position = "right",
        legend.direction = "vertical") 

```

### To be PCA
```{r}
pca_fit <- ncbi_joined_aug |>
  select(where(is.numeric)) |>
  prcomp(scale = TRUE)

pca_fit_augment <- pca_fit |> 
  augment(ncbi_joined_aug)

pca_fit_augment  |> 
  ggplot(aes(x=.fittedPC1, 
             y=.fittedPC2)) + 
  geom_point() +
  theme_bw() +
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 0)

summary()
```
